Variables:
  Stores information that varies with each time.

Examples:
-
  name: Add dns server via a variable
  hosts: localhost
  vars:
    dns_server: 10.1.250.10
  tasks:
    - lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver {{ dns_server }}'

Example2:
#Sample Inventory File
Web.yml
http_port=8081
snmp_port=161-162
inter_ip_range=192.0.2.0

-
  name: Set firewall Configurations
  hosts: localhost
  tasks:
    - firewalld:
        service: https
        permanent: true
        state: enabled

    - firewalld:
        port: '{{ http_port }}'/tcp
        permanent: true
        state: disabled

    - firewalld:
        port: '{{ snmp_port }}'/udp
        permanent: true
        state: disabled

    - firewalld:
        source: '{{ inter_ip_range }}'/24
        zone: internal
        state: enabled

 
